#!usr/bin/env node

const fs = require("fs");
const yaml = require("js-yaml");
const path = require("path");
const { parse } = require("jsona-openapi-js");
const { parseOperations } = require("use-openapi");
const { generate } = require("typegen-openapi");

const yargs = require("yargs")
  .help()
  .usage("$0 <input> [output]", "Generate type file for kisa")
  .positional("input", {
    type: "string",
    describe: "openapi json/yaml/jsona file",
  })
  .positional("output", {
    type: "string",
    description: "output d.ts file",
  });

function load(file) {
  const ext = path.extname(file);
  const content = fs.readFileSync(file, "utf8");
  if (ext === ".json") {
    return JSON.parse(ext);
  } else if (ext === ".yaml" || ext === ".yml") {
    return yaml.load(content);
  } else if (ext === ".jsona") {
    return parse(content);
  }
}

function render(spec) {
  let content = `/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  KisaHandler,
  KisaHandlers,
  KisaMiddlewares,
  KisaMiddleware,
  KisaSecurityHandlers,
} from "kisa";

`;

  content += generate(spec, {
    handlers: `export interface Handlers<S> extends KisaHandlers<S> {<% list.forEach(function(name) { %>
  <%= name %>: KisaHandler<S, <%= cases.pascalCase(name) %>Req>; <% });%>}`,
    middlewares: `export interface Middlewares<S> extends KisaMiddlewares<S> {<% list.forEach(function(name) { %>
  <%= name %>: KisaMiddleware<S>; <% });%>}`,
    securityHandlers: `export interface SecurityHandlers<S> extends KisaSecurityHandlers<S> {<% list.forEach(function(name) { %>
  <%= name %>: (config: string[]) => KisaMiddleware<S>; <% });%>}`,
  });

  return content;
}

function run(argv) {
  const spec = load(argv.input);
  let content = render(spec);
  const operations = parseOperations(spec);
  content += `

export const OPERATIONS = \`${JSON.stringify(operations)}\`;
`;
  if (argv.output) {
    fs.writeFileSync(argv.output, content);
  } else {
    console.log(content);
  }
}

if (require.main === module) {
  const argv = yargs.parse(process.argv.slice(2));
  run(argv);
} else {
  module.exports = { yargs, run };
}
